version: '3.8'

services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: vCm7puY3GqZHjA
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgresql://postgres:vCm7puY3GqZHjA@localhost/postgres"]
      interval: 3s
      timeout: 30s
      retries: 10
      start_period: 80s
    volumes:
      - "postgres-db:/data/postgres"
    # DEV only
    ports:
      - "5432:5432"

volumes:
  postgres-db:
